name: expense_tracker
description: "Expense Tracker - A cross-platform expense management app."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  grpc: ^4.1.0
  # grpc_web: ^0.3.4
  intl: ^0.20.1
  protobuf: ^4.1.0
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  protoc_plugin: ^22.0.0

flutter:
  uses-material-design: true
